name: Publish OpenAPI Spec
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn

      - name: Generate OpenAPI spec
        run: |
          python -c "import json; from main import app; print(json.dumps(app.openapi(), indent=2))" > openapi.json

      - name: Upload OpenAPI spec
        uses: actions/upload-artifact@v3
        with:
          name: openapi-spec
          path: openapi.json
