name: Update API Documentation

on:
  push:
    branches: [main]
    paths:
      - 'src/todo_api/**/*.py'
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout API repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install API
        run: |
          pip install uv
          uv pip install -e .

      - name: Generate OpenAPI spec
        run: |
          python -c "
          import json
          from src.todo_api.main import app
          
          with open('openapi.json', 'w') as f:
              json.dump(app.openapi(), f, indent=2)
          "

      - name: Checkout docs repository
        uses: actions/checkout@v4
        with:
          repository: sid2harthgupta/docs
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          path: docs

      - name: Update OpenAPI spec
        run: |
          cp openapi.json docs/api-reference/openapi.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          path: docs
          commit-message: 'chore: update OpenAPI specification'
          title: '📚 Update API Documentation'
          body: 'Updates OpenAPI spec from todo-api@${{ github.sha }}'
          branch: update-api-docs-${{ github.run_number }}
          delete-branch: true
