name: Update API Documentation
on:
  push:
    branches: [main]
    paths:
      - 'src/todo_api/**/*.py'
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout todo-api
        uses: actions/checkout@v3
        with:
          path: todo-api

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: todo-api
        run: |
          pip install fastapi

      - name: Create generation script
        run: |
          cat > generate_docs.py << 'EOF'
          import json
          import sys
          import os
          
          # Add source to path
          sys.path.insert(0, 'todo-api/src')
          from todo_api.main import app
          
          # Generate OpenAPI schema
          openapi_schema = app.openapi()
          
          # Save OpenAPI spec
          with open('openapi.json', 'w') as f:
              json.dump(openapi_schema, f, indent=2)
          
          # Create endpoint MDX files
          os.makedirs('endpoint-files', exist_ok=True)
          
          # Map of endpoints to generate
          endpoints = []
          endpoint_mapping = {
              'get': {'filename': 'get-todo.mdx', 'title': 'Get Todo'},
              'post': {'filename': 'create-todo.mdx', 'title': 'Create Todo'},
              'delete': {'filename': 'delete-todo.mdx', 'title': 'Delete Todo'},
              'put': {'filename': 'update-todo.mdx', 'title': 'Update Todo'},
              'patch': {'filename': 'patch-todo.mdx', 'title': 'Patch Todo'}
          }
          
          for path, methods in openapi_schema['paths'].items():
              for method, details in methods.items():
                  method_lower = method.lower()
                  if method_lower in endpoint_mapping:
                      filename = endpoint_mapping[method_lower]['filename']
                      title = endpoint_mapping[method_lower]['title']
                      
                      # Override title if summary exists
                      if 'summary' in details:
                          title = details['summary']
                      
                      # Create MDX content
                      mdx_content = f"""---
          title: '{title}'
          openapi: '{method.upper()} {path}'
          ---
          """
                      
                      # Write MDX file
                      with open(f'endpoint-files/{filename}', 'w') as f:
                          f.write(mdx_content)
                      
                      endpoints.append({
                          'file': f'api-reference/endpoint/{filename[:-4]}',
                          'title': title
                      })
          
          print('Generated endpoint files:', endpoints)
          print('OpenAPI spec generated successfully')
          EOF

      - name: Generate OpenAPI and endpoint files
        run: python generate_docs.py

      - name: Checkout docs repository
        uses: actions/checkout@v4
        with:
          repository: sid2harthgupta/docs
          token: ${{ secrets.DOCS_PUSH_TOKEN }}
          path: docs

      - name: Update documentation
        run: |
          # Copy OpenAPI spec
          cp openapi.json docs/api-reference/openapi.json
          
          # Copy endpoint files
          mkdir -p docs/api-reference/endpoint
          cp endpoint-files/*.mdx docs/api-reference/endpoint/
          
          # List what was updated
          echo "Updated files:"
          ls -la docs/api-reference/openapi.json
          ls -la docs/api-reference/endpoint/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.DOCS_PUSH_TOKEN }}
          path: docs
          commit-message: 'chore: update API documentation'
          branch: update-api-docs-${{ github.sha }}
          title: '📚 Update API Documentation'
          body: |
            ## Automated API Documentation Update
            
            This PR updates the API documentation based on changes in the todo-api repository.
            
            ### Changes:
            - Updated `/api-reference/openapi.json`
            - Generated/updated endpoint MDX files
            
            ### Source commit: ${{ github.sha }}
          base: main
